### ISSUE TITLE
Items are not drawn.

### ISSUE THREAD

**Issue by sleeepapnea** [GreaseMonk/android-timetable-core#14]
Hello, GreaseMonk,
Some items are not drawn after fast scrolling and stop.
You can visualize it in demo apk.

**Comment by GreaseMonk** [comment]
I am aware of the issue, please refer to the notice i wrote in the readme, i'm replacing the whole lot with kotlin, which will get rid of the issue. It's a layout manager issue. Scrolling only a millimeter fixes the issue, but it's because the layout updates have stopped when you scroll fast.
