### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by bidy** [GreaseMonk/android-timetable-core#5]
Hi, thank your for the TiemTable.
Is it possible to add horizontal and vertical scrollbars to the table?

**Comment by GreaseMonk** [comment]
I expect to have free time to look at that next week :-) I'll keep you posted in this thread.

**Comment by bidy** [comment]
Good. Both horizontal and vertical bars at the same time would be great!

**Comment by GreaseMonk** [comment]
I've looked at the problem, and currently native scrollbars are not supported, i'll create a ticket to make a custom scrollbar - I'm sorry for the delay to get back to you @bidy i'm swamped with work

**Comment by GreaseMonk** [comment]
Closed due to inactivity.
