### ISSUE TITLE
on scrolling column issue

### ISSUE THREAD

**Issue by Akshata001** [GreaseMonk/android-timetable-core#7]
After scrolling, column's first item is hidden. Suppose there are total 10 columns initially. Then after scrolling, below grid remains same(i.e. 10), but size of column becomes 9.

**Comment by GreaseMonk** [comment]
Strange, can you visualize it with a screenshot ?
I'm just trying to get an idea how you use the timetable

**Comment by Akshata001** [comment]
Hello actually .. it's the bug in library itself. I have not done so much
modification in that yet...
Please check in library's APK .
Please find the attached  screenshot after scrolling and before scrolling.

And please help me out of this..as soon as possible...as I rely  on this
code.

Thanks & Regards,
Akshata Patil

**Comment by GreaseMonk** [comment]
Is this weekend fine for you that I check it out ?

Thank you for submitting 👍

**Comment by Akshata001** [comment]
till than can u suggest any idea?  as I am currently working on it.

**Comment by GreaseMonk** [comment]
i'm looking into it now - give me an hour and i'll drop another comment

**Comment by Akshata001** [comment]
ok..thanks

**Comment by GreaseMonk** [comment]
@Akshata001 did you download the repository and added it as library, or did you use gradle dependency to add it to your project please ?

**Comment by Akshata001** [comment]
no..I added it as library

**Comment by GreaseMonk** [comment]
can you try and load [this repository](https://github.com/GreaseMonk/android-timetable) in your android studio, and see if the bug is still present ? 
I cannot see the problem at the moment :(

**Comment by Akshata001** [comment]
ok...letme check

**Comment by GreaseMonk** [comment]
that repository includes the library correctly and you can load and launch immediately as an app. 
Make sure to load branch develop.!

**Comment by Akshata001** [comment]
hello I think library is not updated yet right??
Its causing the same issue yet. can u tell me have u made any changes  in library?

**Comment by GreaseMonk** [comment]
I see the problem now - I notice that when i start the app , and start scrolling, the displayed data is quickly reloaded.  today is 28th and that is displayed initially, but upon scrolling, the 28th is hidden.

**Comment by Akshata001** [comment]
and I noticed one thing.. if I scroll exact horizontally, i mean vertical scroll dy=0, than it's no issue.
Whenever dy>0, at that time causing the issue

**Comment by Akshata001** [comment]
sorry I missed your above message..
yes, exactly the same issue is there

**Comment by Akshata001** [comment]
I resolved it.
In Timetable.java . 
Just replaced 
  @Override
      public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
        super.onScrolled(recyclerView, dx, dy);
        if (state == RecyclerView.SCROLL_STATE_IDLE) {
          return;
        }

        final LinearLayoutManager managerX = (LinearLayoutManager) observedList.get(0)
            .getLayoutManager();
        final LinearLayoutManager managerY = (LinearLayoutManager) observedList.get(1)
            .getLayoutManager();
        final FixedGridLayoutManager layoutMgr = (FixedGridLayoutManager) recyclerView
            .getLayoutManager();

        final int firstRow = layoutMgr.getFirstVisibleRow();
        final int firstColumn = layoutMgr.getFirstVisibleColumn();

        View firstVisibleItem = layoutMgr.getChildAt(0);
        if (firstVisibleItem != null) {
          int decoratedY = layoutMgr.getDecoratedBottom(firstVisibleItem);
          int decoratedX = layoutMgr.getDecoratedLeft(firstVisibleItem);

          if (managerX != null) {
            managerX.scrollToPositionWithOffset(firstColumn , decoratedX);
          }
          if (managerY != null) {
            managerY.scrollToPositionWithOffset(firstRow+1 , decoratedY);
          }
        }
      }

Change is in line:
 managerX.scrollToPositionWithOffset(firstColumn , decoratedX);

**Comment by GreaseMonk** [comment]
Thank you for submitting the solution, i'll put it up on the develop branch to be released

👍 👍 👍 👍
