### ISSUE TITLE
Add on long click listener

### ISSUE THREAD

**Issue by loucass003** [GreaseMonk/android-timetable-core#9]
Hi, 

I have an idea, add a long click listener

In GridItem.java : in bindView method
```
holder.itemView.setOnLongClickListener(new View.OnLongClickListener()
{
	@Override
	public boolean onLongClick(View view)
	{
	        model.onLongClick(view);
		return true;
	}
});
```

**Comment by GreaseMonk** [comment]
You can modify the code in a fork to support long click listeners, I will add this to the timetable at a later time though.
